[package]
name = "mqtt_ac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.30"
tokio = { version="1", features = ["full"]}
tokio-stream = "0.1"
serde_json = "1.0"
serde = { version = "1.0.134", features = ["derive"] }
rumqttc = { version = "0.20.0", default-features = false }
